import type { SlashCommand } from "./types.js";
import { getCommandDocUrl } from "./docUrls.js";

const PLATFORM_RELEASE_BASELINES: Record<string, string> = {
  "copilot-vscode": "2024-01-10",
  "copilot-cli": "2024-02-08",
  "copilot-github": "2024-03-14",
  "copilot-vs": "2024-02-21",
  "copilot-jetbrains": "2024-04-02",
  "copilot-xcode": "2024-04-17",
  "claude-code": "2024-10-22",
  "claude-sdk": "2025-01-15",
};

const PLATFORM_RELEASE_VERSIONS: Record<string, string> = {
  "copilot-vscode": "VS Code Copilot 1.0",
  "copilot-cli": "Copilot CLI 1.0",
  "copilot-github": "GitHub Copilot Chat 1.0",
  "copilot-vs": "Visual Studio Copilot 1.0",
  "copilot-jetbrains": "JetBrains Copilot 1.0",
  "copilot-xcode": "Xcode Copilot 1.0",
  "claude-code": "Claude Code GA",
  "claude-sdk": "Claude SDK 1.0",
};

const RECENT_COMMAND_UPDATES: Record<string, string> = {
  "copilot-vscode--setup-tests": "2026-03-08",
  "copilot-vscode--new": "2026-03-06",
  "copilot-vscode--new-notebook": "2026-03-05",
  "copilot-cli--agent": "2026-03-04",
  "copilot-cli--skills": "2026-03-03",
  "claude-code--agents": "2026-03-09",
  "claude-code--hooks": "2026-03-07",
  "claude-code--skills": "2026-03-10",
  "claude-sdk--plan": "2026-03-11",
};

function addDays(dateString: string, offset: number) {
  const date = new Date(`${dateString}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + offset);
  return date.toISOString().slice(0, 10);
}

function daysSince(dateString?: string) {
  if (!dateString) {
    return Number.POSITIVE_INFINITY;
  }

  const timestamp = Date.parse(`${dateString}T00:00:00Z`);
  const now = Date.parse("2026-03-14T00:00:00Z");
  return Math.floor((now - timestamp) / 86_400_000);
}

function getPriority(command: SlashCommand, index: number): SlashCommand["priority"] {
  if (index >= RAW_COMMANDS.length - 12) {
    return "new";
  }

  if (command.category === "code-action" || command.category === "planning") {
    return "essential";
  }

  if (command.category === "help" || command.category === "session") {
    return "common";
  }

  return "niche";
}

function getWorkspaceWeight(command: SlashCommand) {
  const platformWeight =
    command.platform === "copilot-vscode"
      ? 10
      : command.platform === "copilot-cli"
        ? 8
        : command.platform === "claude-code"
          ? 7
          : command.platform === "copilot-github"
            ? 5
            : 4;

  const categoryWeight =
    command.category === "code-action"
      ? 5
      : command.category === "planning"
        ? 4
        : command.category === "session"
          ? 3
          : 1;

  return platformWeight + categoryWeight;
}

function enrichCommand(command: SlashCommand, index: number): SlashCommand {
  const releasedAt =
    command.releasedAt ??
    addDays(PLATFORM_RELEASE_BASELINES[command.platform] ?? "2024-01-01", index);
  const updatedAt = RECENT_COMMAND_UPDATES[command.id] ?? releasedAt;

  return {
    ...command,
    catalogIndex: index,
    releasedAt,
    updatedAt,
    releaseVersion: command.releaseVersion ?? PLATFORM_RELEASE_VERSIONS[command.platform] ?? "Initial release",
    priority: command.priority ?? getPriority(command, index),
    workspaceWeight: command.workspaceWeight ?? getWorkspaceWeight(command),
    isNew: daysSince(releasedAt) <= 45,
    isRecentlyUpdated: daysSince(updatedAt) <= 21,
    docUrl: getCommandDocUrl(command),
  };
}

const RAW_COMMANDS: SlashCommand[] = [
  {
    id: "copilot-vscode--doc",
    command: "/doc",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Generate code documentation comments",
    aliases: [],
    whenToUse: "Use this when you want to generate code documentation comments. It works best for a focused selection, file, or error-driven change.",
    example: "/doc",
    equivalents: ["copilot-vs--doc", "copilot-xcode--doc"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "code-action", "doc", "documentation"],
  },
  {
    id: "copilot-vscode--explain",
    command: "/explain",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Explain a code block, file, or concept",
    aliases: [],
    whenToUse: "Use this when you want to explain a code block, file, or concept. It works best for a focused selection, file, or error-driven change.",
    example: "/explain",
    equivalents: ["copilot-vs--explain", "copilot-jetbrains--explain", "copilot-xcode--explain"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "code-action", "explain", "understanding"],
  },
  {
    id: "copilot-vscode--fix",
    command: "/fix",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Fix code or resolve errors",
    aliases: [],
    whenToUse: "Use this when you want to fix code or resolve errors. It works best for a focused selection, file, or error-driven change.",
    example: "/fix",
    equivalents: ["copilot-vs--fix", "copilot-jetbrains--fix", "copilot-xcode--fix"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "code-action", "fix", "repair"],
  },
  {
    id: "copilot-vscode--tests",
    command: "/tests",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Generate tests for methods/functions",
    aliases: [],
    whenToUse: "Use this when you want to generate tests for methods/functions. It works best for a focused selection, file, or error-driven change.",
    example: "/tests",
    equivalents: ["copilot-vs--tests", "copilot-jetbrains--tests", "copilot-xcode--tests"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "code-action", "tests", "testing"],
  },
  {
    id: "copilot-vscode--setup-tests",
    command: "/setupTests",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Help setting up a testing framework",
    aliases: [],
    whenToUse: "Use this when you need help wiring up a testing framework before asking for generated tests. It works best when a repo is missing the basic test runner, config, or setup files.",
    example: "/setupTests vitest",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "code-action", "setup-tests", "testing-framework"],
  },
  {
    id: "copilot-vscode--clear",
    command: "/clear",
    platform: "copilot-vscode",
    category: "session",
    description: "Start new chat session",
    aliases: [],
    whenToUse: "Use this when you want to start new chat session. It helps when the current chat state is getting in the way of the next task.",
    example: "/clear",
    equivalents: ["copilot-cli--clear", "copilot-github--clear", "copilot-github--new", "claude-code--clear", "claude-sdk--clear"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "session", "clear", "reset"],
  },
  {
    id: "copilot-vscode--compact",
    command: "/compact",
    platform: "copilot-vscode",
    category: "session",
    description: "Compact conversation by summarizing",
    aliases: [],
    whenToUse: "Use this when you want to compact conversation by summarizing. It helps when the current chat state is getting in the way of the next task.",
    example: "/compact focus on the auth module",
    equivalents: ["copilot-cli--compact", "claude-code--compact", "claude-sdk--compact"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "session", "compact", "summarization"],
  },
  {
    id: "copilot-vscode--fork",
    command: "/fork",
    platform: "copilot-vscode",
    category: "session",
    description: "Fork chat session into new independent session",
    aliases: [],
    whenToUse: "Use this when you want to fork chat session into new independent session. It helps when the current chat state is getting in the way of the next task.",
    example: "/fork",
    equivalents: ["claude-code--fork"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "session", "fork", "branching"],
  },
  {
    id: "copilot-vscode--debug",
    command: "/debug",
    platform: "copilot-vscode",
    category: "help",
    description: "Show Chat Debug view for troubleshooting",
    aliases: [],
    whenToUse: "Use this when you want to show Chat Debug view for troubleshooting. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/debug",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "help", "debug", "troubleshooting"],
  },
  {
    id: "copilot-vscode--new",
    command: "/new",
    platform: "copilot-vscode",
    category: "scaffolding",
    description: "Scaffold new workspace or file",
    aliases: [],
    whenToUse: "Use this when you want to scaffold new workspace or file. It is a fast way to create a strong starting point instead of building from scratch.",
    example: "/new React component",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "scaffolding", "new", "generator"],
  },
  {
    id: "copilot-vscode--new-notebook",
    command: "/newNotebook",
    platform: "copilot-vscode",
    category: "scaffolding",
    description: "Scaffold new Jupyter notebook",
    aliases: [],
    whenToUse: "Use this when you want to scaffold new Jupyter notebook. It is a fast way to create a strong starting point instead of building from scratch.",
    example: "/newNotebook data exploration",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "scaffolding", "new-notebook", "notebook"],
  },
  {
    id: "copilot-vscode--search",
    command: "/search",
    platform: "copilot-vscode",
    category: "scaffolding",
    description: "Generate search query for Search view",
    aliases: [],
    whenToUse: "Use this when you want to generate search query for Search view. It is a fast way to create a strong starting point instead of building from scratch.",
    example: "/search find the auth middleware",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "scaffolding", "search"],
  },
  {
    id: "copilot-vscode--start-debugging",
    command: "/startDebugging",
    platform: "copilot-vscode",
    category: "scaffolding",
    description: "Generate launch.json and start debugging",
    aliases: [],
    whenToUse: "Use this when you want to generate launch.json and start debugging. It is a fast way to create a strong starting point instead of building from scratch.",
    example: "/startDebugging",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "scaffolding", "start-debugging", "debugging"],
  },
  {
    id: "copilot-vscode--plan",
    command: "/plan",
    platform: "copilot-vscode",
    category: "planning",
    description: "Create detailed implementation plan",
    aliases: [],
    whenToUse: "Use this when you want to create detailed implementation plan. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/plan add command filtering by platform",
    equivalents: ["copilot-cli--plan", "claude-code--plan", "claude-sdk--plan"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "planning", "plan", "implementation-plan"],
  },
  {
    id: "copilot-vscode--init",
    command: "/init",
    platform: "copilot-vscode",
    category: "planning",
    description: "Generate/update workspace instructions",
    aliases: [],
    whenToUse: "Use this when you want to generate/update workspace instructions. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/init",
    equivalents: ["copilot-cli--init", "claude-code--init"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "planning", "init", "workspace-instructions"],
  },
  {
    id: "copilot-vscode--agents",
    command: "/agents",
    platform: "copilot-vscode",
    category: "customization",
    description: "Configure custom agents",
    aliases: [],
    whenToUse: "Use this when you want to configure custom agents. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/agents",
    equivalents: ["copilot-cli--agent", "claude-code--agents"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "agents"],
  },
  {
    id: "copilot-vscode--hooks",
    command: "/hooks",
    platform: "copilot-vscode",
    category: "customization",
    description: "Configure hooks",
    aliases: [],
    whenToUse: "Use this when you want to configure hooks. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/hooks",
    equivalents: ["claude-code--hooks"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "hooks"],
  },
  {
    id: "copilot-vscode--instructions",
    command: "/instructions",
    platform: "copilot-vscode",
    category: "customization",
    description: "Configure custom instructions",
    aliases: [],
    whenToUse: "Use this when you want to configure custom instructions. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/instructions",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "instructions"],
  },
  {
    id: "copilot-vscode--prompts",
    command: "/prompts",
    platform: "copilot-vscode",
    category: "customization",
    description: "Configure reusable prompt files",
    aliases: [],
    whenToUse: "Use this when you want to configure reusable prompt files. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/prompts",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "prompts"],
  },
  {
    id: "copilot-vscode--skills",
    command: "/skills",
    platform: "copilot-vscode",
    category: "customization",
    description: "Configure agent skills",
    aliases: [],
    whenToUse: "Use this when you want to configure agent skills. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/skills",
    equivalents: ["copilot-cli--skills", "claude-code--skills"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "skills"],
  },
  {
    id: "copilot-vscode--create-prompt",
    command: "/create-prompt",
    platform: "copilot-vscode",
    category: "customization",
    description: "Generate a prompt file with AI",
    aliases: [],
    whenToUse: "Use this when you want to generate a prompt file with AI. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/create-prompt release notes prompt",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "create-prompt", "generator"],
  },
  {
    id: "copilot-vscode--create-instruction",
    command: "/create-instruction",
    platform: "copilot-vscode",
    category: "customization",
    description: "Generate instructions file with AI",
    aliases: [],
    whenToUse: "Use this when you want to generate instructions file with AI. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/create-instruction repo guidelines",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "create-instruction", "generator"],
  },
  {
    id: "copilot-vscode--create-skill",
    command: "/create-skill",
    platform: "copilot-vscode",
    category: "customization",
    description: "Generate agent skill with AI",
    aliases: [],
    whenToUse: "Use this when you want to generate agent skill with AI. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/create-skill changelog analyzer",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "create-skill", "generator"],
  },
  {
    id: "copilot-vscode--create-agent",
    command: "/create-agent",
    platform: "copilot-vscode",
    category: "customization",
    description: "Generate custom agent with AI",
    aliases: [],
    whenToUse: "Use this when you want to generate custom agent with AI. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/create-agent reviewer",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "create-agent", "generator"],
  },
  {
    id: "copilot-vscode--create-hook",
    command: "/create-hook",
    platform: "copilot-vscode",
    category: "customization",
    description: "Generate hook config with AI",
    aliases: [],
    whenToUse: "Use this when you want to generate hook config with AI. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/create-hook post-edit lint",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "customization", "create-hook", "generator"],
  },
  {
    id: "copilot-vscode--yolo",
    command: "/yolo",
    platform: "copilot-vscode",
    category: "permissions",
    description: "Enable global auto-approval",
    aliases: ["/autoApprove"],
    whenToUse: "Use this when you want to enable global auto-approval. It is a quick way to control how much autonomy the assistant has.",
    example: "/yolo",
    equivalents: ["copilot-cli--allow-all", "claude-code--permissions"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "permissions", "yolo", "auto-approval"],
  },
  {
    id: "copilot-vscode--disable-yolo",
    command: "/disableYolo",
    platform: "copilot-vscode",
    category: "permissions",
    description: "Disable global auto-approval",
    aliases: ["/disableAutoApprove"],
    whenToUse: "Use this when you want to disable global auto-approval. It is a quick way to control how much autonomy the assistant has.",
    example: "/disableYolo",
    equivalents: ["copilot-cli--reset-allowed-tools", "claude-code--permissions"],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_slash-commands",
    tags: ["slash-command", "copilot-vscode", "permissions", "disable-yolo", "auto-approval"],
  },
  {
    id: "copilot-cli--clear",
    command: "/clear",
    platform: "copilot-cli",
    category: "session",
    description: "Clear conversation history",
    aliases: ["/new"],
    whenToUse: "Use this when you want to clear conversation history. It helps when the current chat state is getting in the way of the next task.",
    example: "/clear",
    equivalents: ["copilot-vscode--clear", "copilot-github--clear", "copilot-github--new", "claude-code--clear", "claude-sdk--clear"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "clear", "reset"],
  },
  {
    id: "copilot-cli--compact",
    command: "/compact",
    platform: "copilot-cli",
    category: "session",
    description: "Summarize conversation to reduce context",
    aliases: [],
    whenToUse: "Use this when you want to summarize conversation to reduce context. It helps when the current chat state is getting in the way of the next task.",
    example: "/compact focus on the auth module",
    equivalents: ["copilot-vscode--compact", "claude-code--compact", "claude-sdk--compact"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "compact", "summarization"],
  },
  {
    id: "copilot-cli--context",
    command: "/context",
    platform: "copilot-cli",
    category: "session",
    description: "Show context window token usage",
    aliases: [],
    whenToUse: "Use this when you want to show context window token usage. It helps when the current chat state is getting in the way of the next task.",
    example: "/context",
    equivalents: ["claude-code--context"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "context", "tokens"],
  },
  {
    id: "copilot-cli--exit",
    command: "/exit",
    platform: "copilot-cli",
    category: "session",
    description: "Exit the CLI",
    aliases: ["/quit"],
    whenToUse: "Use this when you want to exit the CLI. It helps when the current chat state is getting in the way of the next task.",
    example: "/exit",
    equivalents: ["claude-code--exit"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "exit", "quit"],
  },
  {
    id: "copilot-cli--rename",
    command: "/rename",
    platform: "copilot-cli",
    category: "session",
    description: "Rename current session",
    aliases: [],
    whenToUse: "Use this when you want to rename current session. It helps when the current chat state is getting in the way of the next task.",
    example: "/rename slash command dataset",
    equivalents: ["copilot-github--rename", "claude-code--rename"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "rename", "session-name"],
  },
  {
    id: "copilot-cli--resume",
    command: "/resume",
    platform: "copilot-cli",
    category: "session",
    description: "Switch to different session",
    aliases: [],
    whenToUse: "Use this when you want to switch to different session. It helps when the current chat state is getting in the way of the next task.",
    example: "/resume slash-command-research",
    equivalents: ["claude-code--resume"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "session", "resume", "session-switch"],
  },
  {
    id: "copilot-cli--add-dir",
    command: "/add-dir",
    platform: "copilot-cli",
    category: "directory",
    description: "Add directory to allowed list",
    aliases: [],
    whenToUse: "Use this when you want to add directory to allowed list. Use it when the assistant needs the right folder scope or you want to confirm access.",
    example: "/add-dir C:\\Users\\breif\\my-project-ecosystem",
    equivalents: ["claude-code--add-dir"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "directory", "add-dir", "allowlist"],
  },
  {
    id: "copilot-cli--list-dirs",
    command: "/list-dirs",
    platform: "copilot-cli",
    category: "directory",
    description: "Display allowed directories",
    aliases: [],
    whenToUse: "Use this when you want to display allowed directories. Use it when the assistant needs the right folder scope or you want to confirm access.",
    example: "/list-dirs",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "directory", "list-dirs", "allowlist"],
  },
  {
    id: "copilot-cli--cwd",
    command: "/cwd",
    platform: "copilot-cli",
    category: "directory",
    description: "Show/change working directory",
    aliases: ["/cd"],
    whenToUse: "Use this when you want to show/change working directory. Use it when the assistant needs the right folder scope or you want to confirm access.",
    example: "/cwd C:\\Users\\breif\\my-project-ecosystem\\slash-cards",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "directory", "cwd", "working-directory"],
  },
  {
    id: "copilot-cli--model",
    command: "/model",
    platform: "copilot-cli",
    category: "config",
    description: "Select AI model",
    aliases: ["/models"],
    whenToUse: "Use this when you want to select AI model. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/model gpt-5",
    equivalents: ["claude-code--model", "claude-sdk--model"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "config", "model", "models"],
  },
  {
    id: "copilot-cli--theme",
    command: "/theme",
    platform: "copilot-cli",
    category: "config",
    description: "View/configure terminal theme",
    aliases: [],
    whenToUse: "Use this when you want to view/configure terminal theme. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/theme dark",
    equivalents: ["claude-code--theme"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "config", "theme", "appearance"],
  },
  {
    id: "copilot-cli--terminal-setup",
    command: "/terminal-setup",
    platform: "copilot-cli",
    category: "config",
    description: "Configure multiline input",
    aliases: [],
    whenToUse: "Use this when you want to configure multiline input. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/terminal-setup",
    equivalents: ["claude-code--terminal-setup"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "config", "terminal-setup", "terminal"],
  },
  {
    id: "copilot-cli--experimental",
    command: "/experimental",
    platform: "copilot-cli",
    category: "config",
    description: "Toggle experimental features",
    aliases: [],
    whenToUse: "Use this when you want to toggle experimental features. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/experimental",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "config", "experimental", "feature-flags"],
  },
  {
    id: "copilot-cli--reset-allowed-tools",
    command: "/reset-allowed-tools",
    platform: "copilot-cli",
    category: "permissions",
    description: "Reset tool permissions",
    aliases: [],
    whenToUse: "Use this when you want to reset tool permissions. It is a quick way to control how much autonomy the assistant has.",
    example: "/reset-allowed-tools",
    equivalents: ["copilot-vscode--disable-yolo", "claude-code--permissions"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "permissions", "reset-allowed-tools", "tools"],
  },
  {
    id: "copilot-cli--allow-all",
    command: "/allow-all",
    platform: "copilot-cli",
    category: "permissions",
    description: "Enable all permissions",
    aliases: ["/yolo"],
    whenToUse: "Use this when you want to enable all permissions. It is a quick way to control how much autonomy the assistant has.",
    example: "/allow-all",
    equivalents: ["copilot-vscode--yolo", "claude-code--permissions"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "permissions", "allow-all", "auto-approval"],
  },
  {
    id: "copilot-cli--plan",
    command: "/plan",
    platform: "copilot-cli",
    category: "planning",
    description: "Create implementation plan",
    aliases: [],
    whenToUse: "Use this when you want to create implementation plan. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/plan add command filtering by platform",
    equivalents: ["copilot-vscode--plan", "claude-code--plan", "claude-sdk--plan"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "planning", "plan", "implementation-plan"],
  },
  {
    id: "copilot-cli--review",
    command: "/review",
    platform: "copilot-cli",
    category: "planning",
    description: "Run code review agent",
    aliases: [],
    whenToUse: "Use this when you want to run code review agent. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/review",
    equivalents: ["copilot-cli--diff", "claude-code--security-review", "claude-code--diff"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "planning", "review"],
  },
  {
    id: "copilot-cli--diff",
    command: "/diff",
    platform: "copilot-cli",
    category: "planning",
    description: "Review changes in current directory",
    aliases: [],
    whenToUse: "Use this when you want to review changes in current directory. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/diff",
    equivalents: ["copilot-cli--review", "claude-code--security-review", "claude-code--diff"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "planning", "diff", "changes"],
  },
  {
    id: "copilot-cli--init",
    command: "/init",
    platform: "copilot-cli",
    category: "planning",
    description: "Initialize custom instructions",
    aliases: [],
    whenToUse: "Use this when you want to initialize custom instructions. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/init",
    equivalents: ["copilot-vscode--init", "claude-code--init"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "planning", "init", "instructions"],
  },
  {
    id: "copilot-cli--delegate",
    command: "/delegate",
    platform: "copilot-cli",
    category: "collaboration",
    description: "Create AI-generated PR",
    aliases: [],
    whenToUse: "Use this when you want to create AI-generated PR. It helps when you need to hand work off, share results, or coordinate with teammates.",
    example: "/delegate",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "collaboration", "delegate", "pull-request"],
  },
  {
    id: "copilot-cli--share",
    command: "/share",
    platform: "copilot-cli",
    category: "collaboration",
    description: "Share session to file or gist",
    aliases: [],
    whenToUse: "Use this when you want to share session to file or gist. It helps when you need to hand work off, share results, or coordinate with teammates.",
    example: "/share session-summary.md",
    equivalents: ["claude-code--export"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "collaboration", "share", "sharing"],
  },
  {
    id: "copilot-cli--fleet",
    command: "/fleet",
    platform: "copilot-cli",
    category: "collaboration",
    description: "Parallel subagent execution",
    aliases: [],
    whenToUse: "Use this when you want to parallel subagent execution. It helps when you need to hand work off, share results, or coordinate with teammates.",
    example: "/fleet build comparison cards",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "collaboration", "fleet", "parallel"],
  },
  {
    id: "copilot-cli--mcp",
    command: "/mcp",
    platform: "copilot-cli",
    category: "integration",
    description: "Manage MCP server config",
    aliases: [],
    whenToUse: "Use this when you want to manage MCP server config. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/mcp list",
    equivalents: ["claude-code--mcp"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "mcp"],
  },
  {
    id: "copilot-cli--agent",
    command: "/agent",
    platform: "copilot-cli",
    category: "integration",
    description: "Browse/select agents",
    aliases: [],
    whenToUse: "Use this when you want to browse/select agents. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/agent list",
    equivalents: ["copilot-vscode--agents", "claude-code--agents"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "agent", "agents"],
  },
  {
    id: "copilot-cli--ide",
    command: "/ide",
    platform: "copilot-cli",
    category: "integration",
    description: "Connect to IDE workspace",
    aliases: [],
    whenToUse: "Use this when you want to connect to IDE workspace. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/ide connect",
    equivalents: ["claude-code--ide"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "ide"],
  },
  {
    id: "copilot-cli--lsp",
    command: "/lsp",
    platform: "copilot-cli",
    category: "integration",
    description: "Manage language server config",
    aliases: [],
    whenToUse: "Use this when you want to manage language server config. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/lsp list",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "lsp", "language-server"],
  },
  {
    id: "copilot-cli--plugin",
    command: "/plugin",
    platform: "copilot-cli",
    category: "integration",
    description: "Manage plugins",
    aliases: [],
    whenToUse: "Use this when you want to manage plugins. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/plugin list",
    equivalents: ["claude-code--plugin"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "plugin", "plugins"],
  },
  {
    id: "copilot-cli--skills",
    command: "/skills",
    platform: "copilot-cli",
    category: "integration",
    description: "Manage skills",
    aliases: [],
    whenToUse: "Use this when you want to manage skills. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/skills list",
    equivalents: ["copilot-vscode--skills", "claude-code--skills"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "integration", "skills"],
  },
  {
    id: "copilot-cli--login",
    command: "/login",
    platform: "copilot-cli",
    category: "auth",
    description: "Log in to Copilot",
    aliases: [],
    whenToUse: "Use this when you want to log in to Copilot. Use it while signing in, switching accounts, or managing product access.",
    example: "/login",
    equivalents: ["claude-code--login"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "auth", "login", "signin"],
  },
  {
    id: "copilot-cli--logout",
    command: "/logout",
    platform: "copilot-cli",
    category: "auth",
    description: "Log out of Copilot",
    aliases: [],
    whenToUse: "Use this when you want to log out of Copilot. Use it while signing in, switching accounts, or managing product access.",
    example: "/logout",
    equivalents: ["claude-code--logout"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "auth", "logout", "signout"],
  },
  {
    id: "copilot-cli--user",
    command: "/user",
    platform: "copilot-cli",
    category: "auth",
    description: "Manage GitHub user",
    aliases: [],
    whenToUse: "Use this when you want to manage GitHub user. Use it while signing in, switching accounts, or managing product access.",
    example: "/user",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "auth", "user", "account"],
  },
  {
    id: "copilot-cli--session",
    command: "/session",
    platform: "copilot-cli",
    category: "telemetry",
    description: "Show session info",
    aliases: [],
    whenToUse: "Use this when you want to show session info. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/session",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "telemetry", "session", "session-metadata"],
  },
  {
    id: "copilot-cli--usage",
    command: "/usage",
    platform: "copilot-cli",
    category: "telemetry",
    description: "Display usage metrics",
    aliases: [],
    whenToUse: "Use this when you want to display usage metrics. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/usage",
    equivalents: ["claude-code--usage"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "telemetry", "usage", "metrics"],
  },
  {
    id: "copilot-cli--help",
    command: "/help",
    platform: "copilot-cli",
    category: "help",
    description: "Show help for commands",
    aliases: [],
    whenToUse: "Use this when you want to show help for commands. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/help",
    equivalents: ["copilot-vs--help", "copilot-jetbrains--help", "claude-code--help"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "help", "reference"],
  },
  {
    id: "copilot-cli--feedback",
    command: "/feedback",
    platform: "copilot-cli",
    category: "help",
    description: "Provide feedback",
    aliases: [],
    whenToUse: "Use this when you want to provide feedback. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/feedback",
    equivalents: ["claude-code--feedback"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-the-cli/using-github-copilot-in-the-cli",
    tags: ["slash-command", "copilot-cli", "help", "feedback"],
  },
  {
    id: "copilot-github--clear",
    command: "/clear",
    platform: "copilot-github",
    category: "session",
    description: "Clear conversation",
    aliases: [],
    whenToUse: "Use this when you want to clear conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/clear",
    equivalents: ["copilot-vscode--clear", "copilot-cli--clear", "copilot-github--new", "claude-code--clear", "claude-sdk--clear"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-chat/use-github-copilot-chat-in-githubcom",
    tags: ["slash-command", "copilot-github", "session", "clear", "reset"],
  },
  {
    id: "copilot-github--delete",
    command: "/delete",
    platform: "copilot-github",
    category: "session",
    description: "Delete conversation",
    aliases: [],
    whenToUse: "Use this when you want to delete conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/delete",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-chat/use-github-copilot-chat-in-githubcom",
    tags: ["slash-command", "copilot-github", "session", "delete"],
  },
  {
    id: "copilot-github--new",
    command: "/new",
    platform: "copilot-github",
    category: "session",
    description: "Start new conversation",
    aliases: [],
    whenToUse: "Use this when you want to start new conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/new",
    equivalents: ["copilot-vscode--clear", "copilot-cli--clear", "copilot-github--clear", "claude-code--clear", "claude-sdk--clear"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-chat/use-github-copilot-chat-in-githubcom",
    tags: ["slash-command", "copilot-github", "session", "new", "conversation"],
  },
  {
    id: "copilot-github--rename",
    command: "/rename",
    platform: "copilot-github",
    category: "session",
    description: "Rename conversation",
    aliases: [],
    whenToUse: "Use this when you want to rename conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/rename slash command research",
    equivalents: ["copilot-cli--rename", "claude-code--rename"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-chat/use-github-copilot-chat-in-githubcom",
    tags: ["slash-command", "copilot-github", "session", "rename", "conversation"],
  },
  {
    id: "copilot-vs--doc",
    command: "/doc",
    platform: "copilot-vs",
    category: "code-action",
    description: "Add documentation comment",
    aliases: [],
    whenToUse: "Use this when you want to add documentation comment. It works best for a focused selection, file, or error-driven change.",
    example: "/doc",
    equivalents: ["copilot-vscode--doc", "copilot-xcode--doc"],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "code-action", "doc", "documentation"],
  },
  {
    id: "copilot-vs--explain",
    command: "/explain",
    platform: "copilot-vs",
    category: "code-action",
    description: "Explain code",
    aliases: [],
    whenToUse: "Use this when you want to explain code. It works best for a focused selection, file, or error-driven change.",
    example: "/explain",
    equivalents: ["copilot-vscode--explain", "copilot-jetbrains--explain", "copilot-xcode--explain"],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "code-action", "explain", "understanding"],
  },
  {
    id: "copilot-vs--fix",
    command: "/fix",
    platform: "copilot-vs",
    category: "code-action",
    description: "Fix code problems",
    aliases: [],
    whenToUse: "Use this when you want to fix code problems. It works best for a focused selection, file, or error-driven change.",
    example: "/fix",
    equivalents: ["copilot-vscode--fix", "copilot-jetbrains--fix", "copilot-xcode--fix"],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "code-action", "fix", "repair"],
  },
  {
    id: "copilot-vs--help",
    command: "/help",
    platform: "copilot-vs",
    category: "help",
    description: "Quick reference",
    aliases: [],
    whenToUse: "Use this when you need a quick reference for the available chat commands. It is handy when you remember the feature but not the exact slash command name.",
    example: "/help",
    equivalents: ["copilot-cli--help", "copilot-jetbrains--help", "claude-code--help"],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "help", "reference"],
  },
  {
    id: "copilot-vs--optimize",
    command: "/optimize",
    platform: "copilot-vs",
    category: "code-action",
    description: "Improve running time",
    aliases: [],
    whenToUse: "Use this when you want to improve running time. It works best for a focused selection, file, or error-driven change.",
    example: "/optimize",
    equivalents: [],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "code-action", "optimize", "performance"],
  },
  {
    id: "copilot-vs--tests",
    command: "/tests",
    platform: "copilot-vs",
    category: "code-action",
    description: "Generate unit tests",
    aliases: [],
    whenToUse: "Use this when you want to generate unit tests. It works best for a focused selection, file, or error-driven change.",
    example: "/tests",
    equivalents: ["copilot-vscode--tests", "copilot-jetbrains--tests", "copilot-xcode--tests"],
    docUrl: "https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022",
    tags: ["slash-command", "copilot-vs", "code-action", "tests", "testing"],
  },
  {
    id: "copilot-jetbrains--explain",
    command: "/explain",
    platform: "copilot-jetbrains",
    category: "code-action",
    description: "Explain code",
    aliases: [],
    whenToUse: "Use this when you want to explain code. It works best for a focused selection, file, or error-driven change.",
    example: "/explain",
    equivalents: ["copilot-vscode--explain", "copilot-vs--explain", "copilot-xcode--explain"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=jetbrains",
    tags: ["slash-command", "copilot-jetbrains", "code-action", "explain", "understanding"],
  },
  {
    id: "copilot-jetbrains--fix",
    command: "/fix",
    platform: "copilot-jetbrains",
    category: "code-action",
    description: "Fix code problems",
    aliases: [],
    whenToUse: "Use this when you want to fix code problems. It works best for a focused selection, file, or error-driven change.",
    example: "/fix",
    equivalents: ["copilot-vscode--fix", "copilot-vs--fix", "copilot-xcode--fix"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=jetbrains",
    tags: ["slash-command", "copilot-jetbrains", "code-action", "fix", "repair"],
  },
  {
    id: "copilot-jetbrains--help",
    command: "/help",
    platform: "copilot-jetbrains",
    category: "help",
    description: "Quick reference",
    aliases: [],
    whenToUse: "Use this when you need a quick reference for the available chat commands. It is handy when you remember the feature but not the exact slash command name.",
    example: "/help",
    equivalents: ["copilot-cli--help", "copilot-vs--help", "claude-code--help"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=jetbrains",
    tags: ["slash-command", "copilot-jetbrains", "help", "reference"],
  },
  {
    id: "copilot-jetbrains--tests",
    command: "/tests",
    platform: "copilot-jetbrains",
    category: "code-action",
    description: "Generate unit tests",
    aliases: [],
    whenToUse: "Use this when you want to generate unit tests. It works best for a focused selection, file, or error-driven change.",
    example: "/tests",
    equivalents: ["copilot-vscode--tests", "copilot-vs--tests", "copilot-xcode--tests"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=jetbrains",
    tags: ["slash-command", "copilot-jetbrains", "code-action", "tests", "testing"],
  },
  {
    id: "copilot-xcode--doc",
    command: "/doc",
    platform: "copilot-xcode",
    category: "code-action",
    description: "Generate documentation",
    aliases: [],
    whenToUse: "Use this when you want to generate documentation. It works best for a focused selection, file, or error-driven change.",
    example: "/doc",
    equivalents: ["copilot-vscode--doc", "copilot-vs--doc"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=xcode",
    tags: ["slash-command", "copilot-xcode", "code-action", "doc", "documentation"],
  },
  {
    id: "copilot-xcode--explain",
    command: "/explain",
    platform: "copilot-xcode",
    category: "code-action",
    description: "Explain code",
    aliases: [],
    whenToUse: "Use this when you want to explain code. It works best for a focused selection, file, or error-driven change.",
    example: "/explain",
    equivalents: ["copilot-vscode--explain", "copilot-vs--explain", "copilot-jetbrains--explain"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=xcode",
    tags: ["slash-command", "copilot-xcode", "code-action", "explain", "understanding"],
  },
  {
    id: "copilot-xcode--fix",
    command: "/fix",
    platform: "copilot-xcode",
    category: "code-action",
    description: "Fix code errors",
    aliases: [],
    whenToUse: "Use this when you want to fix code errors. It works best for a focused selection, file, or error-driven change.",
    example: "/fix",
    equivalents: ["copilot-vscode--fix", "copilot-vs--fix", "copilot-jetbrains--fix"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=xcode",
    tags: ["slash-command", "copilot-xcode", "code-action", "fix", "repair"],
  },
  {
    id: "copilot-xcode--simplify",
    command: "/simplify",
    platform: "copilot-xcode",
    category: "code-action",
    description: "Simplify code selection",
    aliases: [],
    whenToUse: "Use this when you want to simplify code selection. It works best for a focused selection, file, or error-driven change.",
    example: "/simplify",
    equivalents: [],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=xcode",
    tags: ["slash-command", "copilot-xcode", "code-action", "simplify", "refactor"],
  },
  {
    id: "copilot-xcode--tests",
    command: "/tests",
    platform: "copilot-xcode",
    category: "code-action",
    description: "Create unit tests",
    aliases: [],
    whenToUse: "Use this when you want to create unit tests. It works best for a focused selection, file, or error-driven change.",
    example: "/tests",
    equivalents: ["copilot-vscode--tests", "copilot-vs--tests", "copilot-jetbrains--tests"],
    docUrl: "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/github-copilot-in-your-ide?tool=xcode",
    tags: ["slash-command", "copilot-xcode", "code-action", "tests", "testing"],
  },
  {
    id: "claude-code--clear",
    command: "/clear",
    platform: "claude-code",
    category: "session",
    description: "Clear conversation history",
    aliases: ["/reset", "/new"],
    whenToUse: "Use this when you want to clear conversation history. It helps when the current chat state is getting in the way of the next task.",
    example: "/clear",
    equivalents: ["copilot-vscode--clear", "copilot-cli--clear", "copilot-github--clear", "copilot-github--new", "claude-sdk--clear"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "clear", "reset"],
  },
  {
    id: "claude-code--compact",
    command: "/compact",
    platform: "claude-code",
    category: "session",
    description: "Compact conversation with optional focus instructions",
    aliases: [],
    whenToUse: "Use this when you want to compact conversation with optional focus instructions. It helps when the current chat state is getting in the way of the next task.",
    example: "/compact focus on the auth module",
    equivalents: ["copilot-vscode--compact", "copilot-cli--compact", "claude-sdk--compact"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "compact", "summarization"],
  },
  {
    id: "claude-code--context",
    command: "/context",
    platform: "claude-code",
    category: "session",
    description: "Visualize context usage as colored grid",
    aliases: [],
    whenToUse: "Use this when you want to visualize context usage as colored grid. It helps when the current chat state is getting in the way of the next task.",
    example: "/context",
    equivalents: ["copilot-cli--context"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "context", "tokens"],
  },
  {
    id: "claude-code--exit",
    command: "/exit",
    platform: "claude-code",
    category: "session",
    description: "Exit CLI",
    aliases: ["/quit"],
    whenToUse: "Use this when you want to exit CLI. It helps when the current chat state is getting in the way of the next task.",
    example: "/exit",
    equivalents: ["copilot-cli--exit"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "exit", "quit"],
  },
  {
    id: "claude-code--fork",
    command: "/fork",
    platform: "claude-code",
    category: "session",
    description: "Fork conversation",
    aliases: [],
    whenToUse: "Use this when you want to fork conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/fork",
    equivalents: ["copilot-vscode--fork"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "fork", "branching"],
  },
  {
    id: "claude-code--rename",
    command: "/rename",
    platform: "claude-code",
    category: "session",
    description: "Rename session",
    aliases: [],
    whenToUse: "Use this when you want to rename session. It helps when the current chat state is getting in the way of the next task.",
    example: "/rename slash command dataset",
    equivalents: ["copilot-cli--rename", "copilot-github--rename"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "rename", "session-name"],
  },
  {
    id: "claude-code--resume",
    command: "/resume",
    platform: "claude-code",
    category: "session",
    description: "Resume conversation",
    aliases: ["/continue"],
    whenToUse: "Use this when you want to resume conversation. It helps when the current chat state is getting in the way of the next task.",
    example: "/resume slash-command-research",
    equivalents: ["copilot-cli--resume"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "resume", "session-switch"],
  },
  {
    id: "claude-code--rewind",
    command: "/rewind",
    platform: "claude-code",
    category: "session",
    description: "Rewind conversation/code",
    aliases: ["/checkpoint"],
    whenToUse: "Use this when you want to rewind conversation/code. It helps when the current chat state is getting in the way of the next task.",
    example: "/rewind",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "session", "rewind", "checkpoint"],
  },
  {
    id: "claude-code--diff",
    command: "/diff",
    platform: "claude-code",
    category: "planning",
    description: "Interactive diff viewer",
    aliases: [],
    whenToUse: "Use this when you want to interactive diff viewer. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/diff",
    equivalents: ["copilot-cli--review", "copilot-cli--diff", "claude-code--security-review"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "planning", "diff", "changes"],
  },
  {
    id: "claude-code--plan",
    command: "/plan",
    platform: "claude-code",
    category: "planning",
    description: "Enter plan mode",
    aliases: [],
    whenToUse: "Use this when you want to enter plan mode. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/plan add command filtering by platform",
    equivalents: ["copilot-vscode--plan", "copilot-cli--plan", "claude-sdk--plan"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "planning", "plan", "implementation-plan"],
  },
  {
    id: "claude-code--security-review",
    command: "/security-review",
    platform: "claude-code",
    category: "planning",
    description: "Analyze changes for vulnerabilities",
    aliases: [],
    whenToUse: "Use this when you want to analyze changes for vulnerabilities. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/security-review",
    equivalents: ["copilot-cli--review", "copilot-cli--diff", "claude-code--diff"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "planning", "security-review", "security"],
  },
  {
    id: "claude-code--init",
    command: "/init",
    platform: "claude-code",
    category: "planning",
    description: "Initialize project with CLAUDE.md",
    aliases: [],
    whenToUse: "Use this when you want to initialize project with CLAUDE.md. It is useful before you code or when you want a higher-level pass on the work.",
    example: "/init",
    equivalents: ["copilot-vscode--init", "copilot-cli--init"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "planning", "init", "claude-md"],
  },
  {
    id: "claude-code--model",
    command: "/model",
    platform: "claude-code",
    category: "config",
    description: "Select/change AI model",
    aliases: [],
    whenToUse: "Use this when you want to select/change AI model. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/model sonnet",
    equivalents: ["copilot-cli--model", "claude-sdk--model"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "model", "models"],
  },
  {
    id: "claude-code--effort",
    command: "/effort",
    platform: "claude-code",
    category: "config",
    description: "Set model effort level",
    aliases: [],
    whenToUse: "Use this when you want to set model effort level. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/effort high",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "effort", "reasoning"],
  },
  {
    id: "claude-code--fast",
    command: "/fast",
    platform: "claude-code",
    category: "config",
    description: "Toggle fast mode",
    aliases: [],
    whenToUse: "Use this when you want to toggle fast mode. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/fast",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "fast", "speed"],
  },
  {
    id: "claude-code--config",
    command: "/config",
    platform: "claude-code",
    category: "config",
    description: "Open Settings",
    aliases: ["/settings"],
    whenToUse: "Use this when you want to open Settings. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/config",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "settings"],
  },
  {
    id: "claude-code--theme",
    command: "/theme",
    platform: "claude-code",
    category: "config",
    description: "Change color theme",
    aliases: [],
    whenToUse: "Use this when you want to change color theme. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/theme dark",
    equivalents: ["copilot-cli--theme"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "theme", "appearance"],
  },
  {
    id: "claude-code--color",
    command: "/color",
    platform: "claude-code",
    category: "config",
    description: "Set prompt bar color",
    aliases: [],
    whenToUse: "Use this when you want to set prompt bar color. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/color blue",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "color", "appearance"],
  },
  {
    id: "claude-code--vim",
    command: "/vim",
    platform: "claude-code",
    category: "config",
    description: "Toggle Vim mode",
    aliases: [],
    whenToUse: "Use this when you want to toggle Vim mode. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/vim",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "vim", "editor"],
  },
  {
    id: "claude-code--keybindings",
    command: "/keybindings",
    platform: "claude-code",
    category: "config",
    description: "Open keybindings config",
    aliases: [],
    whenToUse: "Use this when you want to open keybindings config. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/keybindings",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "keybindings", "keyboard"],
  },
  {
    id: "claude-code--terminal-setup",
    command: "/terminal-setup",
    platform: "claude-code",
    category: "config",
    description: "Configure terminal keybindings",
    aliases: [],
    whenToUse: "Use this when you want to configure terminal keybindings. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/terminal-setup",
    equivalents: ["copilot-cli--terminal-setup"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "terminal-setup", "terminal"],
  },
  {
    id: "claude-code--add-dir",
    command: "/add-dir",
    platform: "claude-code",
    category: "directory",
    description: "Add working directory",
    aliases: [],
    whenToUse: "Use this when you want to add working directory. Use it when the assistant needs the right folder scope or you want to confirm access.",
    example: "/add-dir C:\\Users\\breif\\my-project-ecosystem",
    equivalents: ["copilot-cli--add-dir"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "directory", "add-dir", "allowlist"],
  },
  {
    id: "claude-code--permissions",
    command: "/permissions",
    platform: "claude-code",
    category: "permissions",
    description: "View/update permissions",
    aliases: ["/allowed-tools"],
    whenToUse: "Use this when you want to view/update permissions. It is a quick way to control how much autonomy the assistant has.",
    example: "/permissions",
    equivalents: ["copilot-vscode--yolo", "copilot-cli--allow-all", "copilot-vscode--disable-yolo", "copilot-cli--reset-allowed-tools"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "permissions", "tools"],
  },
  {
    id: "claude-code--mcp",
    command: "/mcp",
    platform: "claude-code",
    category: "integration",
    description: "Manage MCP servers",
    aliases: [],
    whenToUse: "Use this when you want to manage MCP servers. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/mcp list",
    equivalents: ["copilot-cli--mcp"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "mcp"],
  },
  {
    id: "claude-code--ide",
    command: "/ide",
    platform: "claude-code",
    category: "integration",
    description: "Manage IDE integrations",
    aliases: [],
    whenToUse: "Use this when you want to manage IDE integrations. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/ide",
    equivalents: ["copilot-cli--ide"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "ide"],
  },
  {
    id: "claude-code--plugin",
    command: "/plugin",
    platform: "claude-code",
    category: "integration",
    description: "Manage plugins",
    aliases: [],
    whenToUse: "Use this when you want to manage plugins. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/plugin",
    equivalents: ["copilot-cli--plugin"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "plugin", "plugins"],
  },
  {
    id: "claude-code--reload-plugins",
    command: "/reload-plugins",
    platform: "claude-code",
    category: "integration",
    description: "Reload active plugins",
    aliases: [],
    whenToUse: "Use this when you want to reload active plugins. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/reload-plugins",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "reload-plugins", "plugins"],
  },
  {
    id: "claude-code--agents",
    command: "/agents",
    platform: "claude-code",
    category: "integration",
    description: "Manage agent configs",
    aliases: [],
    whenToUse: "Use this when you want to manage agent configs. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/agents",
    equivalents: ["copilot-vscode--agents", "copilot-cli--agent"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "agents"],
  },
  {
    id: "claude-code--hooks",
    command: "/hooks",
    platform: "claude-code",
    category: "integration",
    description: "View hook configs",
    aliases: [],
    whenToUse: "Use this when you want to view hook configs. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/hooks",
    equivalents: ["copilot-vscode--hooks"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "hooks"],
  },
  {
    id: "claude-code--skills",
    command: "/skills",
    platform: "claude-code",
    category: "integration",
    description: "List available skills",
    aliases: [],
    whenToUse: "Use this when you want to list available skills. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/skills",
    equivalents: ["copilot-vscode--skills", "copilot-cli--skills"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "skills"],
  },
  {
    id: "claude-code--memory",
    command: "/memory",
    platform: "claude-code",
    category: "customization",
    description: "Edit CLAUDE.md memory files",
    aliases: [],
    whenToUse: "Use this when you want to edit CLAUDE.md memory files. It is useful when you want persistent behavior tailored to your repo or team.",
    example: "/memory",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "customization", "memory"],
  },
  {
    id: "claude-code--login",
    command: "/login",
    platform: "claude-code",
    category: "auth",
    description: "Sign in to Anthropic",
    aliases: [],
    whenToUse: "Use this when you want to sign in to Anthropic. Use it while signing in, switching accounts, or managing product access.",
    example: "/login",
    equivalents: ["copilot-cli--login"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "auth", "login", "signin"],
  },
  {
    id: "claude-code--logout",
    command: "/logout",
    platform: "claude-code",
    category: "auth",
    description: "Sign out",
    aliases: [],
    whenToUse: "Use this when you want to sign out. Use it while signing in, switching accounts, or managing product access.",
    example: "/logout",
    equivalents: ["copilot-cli--logout"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "auth", "logout", "signout"],
  },
  {
    id: "claude-code--upgrade",
    command: "/upgrade",
    platform: "claude-code",
    category: "auth",
    description: "Open upgrade page",
    aliases: [],
    whenToUse: "Use this when you want to open upgrade page. Use it while signing in, switching accounts, or managing product access.",
    example: "/upgrade",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "auth", "upgrade", "billing"],
  },
  {
    id: "claude-code--privacy-settings",
    command: "/privacy-settings",
    platform: "claude-code",
    category: "auth",
    description: "Privacy settings",
    aliases: [],
    whenToUse: "Use this when you need to review or change privacy settings for your Claude account. It is useful before enabling new workflows or when you want to understand what data is retained.",
    example: "/privacy-settings",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "auth", "privacy-settings", "privacy"],
  },
  {
    id: "claude-code--extra-usage",
    command: "/extra-usage",
    platform: "claude-code",
    category: "auth",
    description: "Configure extra usage",
    aliases: [],
    whenToUse: "Use this when you want to configure extra usage. Use it while signing in, switching accounts, or managing product access.",
    example: "/extra-usage",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "auth", "extra-usage", "billing"],
  },
  {
    id: "claude-code--help",
    command: "/help",
    platform: "claude-code",
    category: "help",
    description: "Show help",
    aliases: [],
    whenToUse: "Use this when you want to show help. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/help",
    equivalents: ["copilot-cli--help", "copilot-vs--help", "copilot-jetbrains--help"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "help", "reference"],
  },
  {
    id: "claude-code--cost",
    command: "/cost",
    platform: "claude-code",
    category: "telemetry",
    description: "Token usage statistics",
    aliases: [],
    whenToUse: "Use this when you need a detailed token-cost breakdown for the current work. It helps you spot expensive sessions before they become a budget problem.",
    example: "/cost",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "cost", "tokens"],
  },
  {
    id: "claude-code--usage",
    command: "/usage",
    platform: "claude-code",
    category: "telemetry",
    description: "Plan usage limits",
    aliases: [],
    whenToUse: "Use this when you need to check plan usage limits before starting more work. It is useful for avoiding throttling or knowing when to switch accounts or plans.",
    example: "/usage",
    equivalents: ["copilot-cli--usage"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "usage", "limits"],
  },
  {
    id: "claude-code--stats",
    command: "/stats",
    platform: "claude-code",
    category: "telemetry",
    description: "Visualize usage and session history",
    aliases: [],
    whenToUse: "Use this when you want to visualize usage and session history. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/stats",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "stats", "history"],
  },
  {
    id: "claude-code--insights",
    command: "/insights",
    platform: "claude-code",
    category: "telemetry",
    description: "Generate session analysis report",
    aliases: [],
    whenToUse: "Use this when you want to generate session analysis report. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/insights",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "insights", "analysis"],
  },
  {
    id: "claude-code--status",
    command: "/status",
    platform: "claude-code",
    category: "telemetry",
    description: "Show version, model, account",
    aliases: [],
    whenToUse: "Use this when you want to show version, model, account. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/status",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "status"],
  },
  {
    id: "claude-code--release-notes",
    command: "/release-notes",
    platform: "claude-code",
    category: "telemetry",
    description: "View changelog",
    aliases: [],
    whenToUse: "Use this when you want to view changelog. It helps when you want visibility into usage, cost, limits, or session state.",
    example: "/release-notes",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "telemetry", "release-notes", "changelog"],
  },
  {
    id: "claude-code--doctor",
    command: "/doctor",
    platform: "claude-code",
    category: "help",
    description: "Diagnose installation",
    aliases: [],
    whenToUse: "Use this when you want to diagnose installation. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/doctor",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "help", "doctor", "diagnostics"],
  },
  {
    id: "claude-code--copy",
    command: "/copy",
    platform: "claude-code",
    category: "unique",
    description: "Copy last response to clipboard",
    aliases: [],
    whenToUse: "Use this when you want to copy last response to clipboard. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/copy",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "copy", "clipboard"],
  },
  {
    id: "claude-code--export",
    command: "/export",
    platform: "claude-code",
    category: "collaboration",
    description: "Export conversation as text",
    aliases: [],
    whenToUse: "Use this when you want to export conversation as text. It helps when you need to hand work off, share results, or coordinate with teammates.",
    example: "/export session.txt",
    equivalents: ["copilot-cli--share"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "collaboration", "export", "sharing"],
  },
  {
    id: "claude-code--feedback",
    command: "/feedback",
    platform: "claude-code",
    category: "help",
    description: "Submit feedback",
    aliases: ["/bug"],
    whenToUse: "Use this when you want to submit feedback. Use it when you need guidance, troubleshooting, or a quick reference.",
    example: "/feedback",
    equivalents: ["copilot-cli--feedback"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "help", "feedback"],
  },
  {
    id: "claude-code--btw",
    command: "/btw",
    platform: "claude-code",
    category: "unique",
    description: "Ask side question without adding to conversation",
    aliases: [],
    whenToUse: "Use this when you want to ask side question without adding to conversation. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/btw what does this acronym mean?",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "btw", "aside"],
  },
  {
    id: "claude-code--pr-comments",
    command: "/pr-comments",
    platform: "claude-code",
    category: "unique",
    description: "Fetch PR comments",
    aliases: [],
    whenToUse: "Use this when you want to fetch PR comments. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/pr-comments",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "pr-comments", "pull-request"],
  },
  {
    id: "claude-code--desktop",
    command: "/desktop",
    platform: "claude-code",
    category: "unique",
    description: "Continue in Desktop app",
    aliases: ["/app"],
    whenToUse: "Use this when you want to continue in Desktop app. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/desktop",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "desktop"],
  },
  {
    id: "claude-code--chrome",
    command: "/chrome",
    platform: "claude-code",
    category: "unique",
    description: "Configure Chrome settings",
    aliases: [],
    whenToUse: "Use this when you want to configure Chrome settings. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/chrome",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "chrome", "browser"],
  },
  {
    id: "claude-code--mobile",
    command: "/mobile",
    platform: "claude-code",
    category: "unique",
    description: "Show mobile app QR code",
    aliases: ["/ios", "/android"],
    whenToUse: "Use this when you want to show mobile app QR code. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/mobile",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "mobile"],
  },
  {
    id: "claude-code--remote-control",
    command: "/remote-control",
    platform: "claude-code",
    category: "unique",
    description: "Enable remote control from claude.ai",
    aliases: ["/rc"],
    whenToUse: "Use this when you want to enable remote control from claude.ai. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/remote-control",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "remote-control", "remote"],
  },
  {
    id: "claude-code--sandbox",
    command: "/sandbox",
    platform: "claude-code",
    category: "unique",
    description: "Toggle sandbox mode",
    aliases: [],
    whenToUse: "Use this when you want to toggle sandbox mode. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/sandbox",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "sandbox"],
  },
  {
    id: "claude-code--install-github-app",
    command: "/install-github-app",
    platform: "claude-code",
    category: "integration",
    description: "Set up Claude GitHub Actions",
    aliases: [],
    whenToUse: "Use this when you want to set up Claude GitHub Actions. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/install-github-app",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "install-github-app", "github"],
  },
  {
    id: "claude-code--install-slack-app",
    command: "/install-slack-app",
    platform: "claude-code",
    category: "integration",
    description: "Install Slack app",
    aliases: [],
    whenToUse: "Use this when you want to install Slack app. Reach for it when you are wiring the assistant into editors, plugins, or external services.",
    example: "/install-slack-app",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "integration", "install-slack-app", "slack"],
  },
  {
    id: "claude-code--tasks",
    command: "/tasks",
    platform: "claude-code",
    category: "unique",
    description: "List background tasks",
    aliases: [],
    whenToUse: "Use this when you want to list background tasks. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/tasks",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "tasks", "background"],
  },
  {
    id: "claude-code--statusline",
    command: "/statusline",
    platform: "claude-code",
    category: "config",
    description: "Configure status line",
    aliases: [],
    whenToUse: "Use this when you want to configure status line. It is handy when you are tuning the tool to match your workflow and environment.",
    example: "/statusline",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "config", "statusline", "appearance"],
  },
  {
    id: "claude-code--stickers",
    command: "/stickers",
    platform: "claude-code",
    category: "unique",
    description: "Order stickers",
    aliases: [],
    whenToUse: "Use this when you want to order stickers. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/stickers",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "stickers", "merch"],
  },
  {
    id: "claude-code--passes",
    command: "/passes",
    platform: "claude-code",
    category: "unique",
    description: "Share free week",
    aliases: [],
    whenToUse: "Use this when you want to share free week. Reach for it for product-specific workflows that do not have a direct Copilot equivalent.",
    example: "/passes",
    equivalents: [],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    tags: ["slash-command", "claude-code", "unique", "passes", "sharing"],
  },
  {
    id: "claude-sdk--compact",
    command: "/compact",
    platform: "claude-sdk",
    category: "session",
    description: "Programmatic compact command that mirrors Claude Code /compact",
    aliases: [],
    whenToUse: "Use this when an SDK-driven workflow needs the same conversation compression behavior as Claude Code. It is helpful when you want to preserve key context while keeping agent calls lightweight.",
    example: "/compact focus on the auth module",
    equivalents: ["copilot-vscode--compact", "copilot-cli--compact", "claude-code--compact"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/sdk",
    tags: ["slash-command", "claude-sdk", "session", "compact", "programmatic", "mirrors-claude-code"],
  },
  {
    id: "claude-sdk--clear",
    command: "/clear",
    platform: "claude-sdk",
    category: "session",
    description: "Programmatic clear command that mirrors Claude Code /clear",
    aliases: [],
    whenToUse: "Use this when an SDK-managed agent session should be reset before a new task starts. It is useful for automation flows that need deterministic session boundaries.",
    example: "/clear",
    equivalents: ["copilot-vscode--clear", "copilot-cli--clear", "copilot-github--clear", "copilot-github--new", "claude-code--clear"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/sdk",
    tags: ["slash-command", "claude-sdk", "session", "clear", "programmatic", "mirrors-claude-code"],
  },
  {
    id: "claude-sdk--model",
    command: "/model",
    platform: "claude-sdk",
    category: "config",
    description: "Programmatic model selection that mirrors Claude Code /model",
    aliases: [],
    whenToUse: "Use this when your application needs to switch models in code instead of through the interactive CLI. It is a good fit for routing, experimentation, or workload-based model selection.",
    example: "/model sonnet",
    equivalents: ["copilot-cli--model", "claude-code--model"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/sdk",
    tags: ["slash-command", "claude-sdk", "config", "model", "programmatic", "mirrors-claude-code"],
  },
  {
    id: "claude-sdk--plan",
    command: "/plan",
    platform: "claude-sdk",
    category: "planning",
    description: "Programmatic plan mode that mirrors Claude Code /plan",
    aliases: [],
    whenToUse: "Use this when an SDK workflow should generate a plan before execution, just like Claude Code. It pairs well with custom commands in .claude/commands/*.md or skills in .claude/skills/*/SKILL.md.",
    example: "/plan build slash command comparison cards",
    equivalents: ["copilot-vscode--plan", "copilot-cli--plan", "claude-code--plan"],
    docUrl: "https://docs.anthropic.com/en/docs/claude-code/sdk",
    tags: ["slash-command", "claude-sdk", "planning", "plan", "programmatic", "mirrors-claude-code"],
  },

  // ── @ Participants (VS Code Copilot) ─────────────────────────────────
  {
    id: "copilot-vscode-@workspace",
    command: "@workspace",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Ask questions about your entire workspace. Copilot searches across files, symbols, and project structure to answer.",
    aliases: [],
    whenToUse: "Use this when you want Copilot to reason across your full project — finding related code, understanding architecture, or locating implementations.",
    example: "@workspace where is the auth middleware defined?",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_workspace",
    tags: ["participant", "copilot-vscode", "code-action", "workspace", "project-wide"],
  },
  {
    id: "copilot-vscode-@terminal",
    command: "@terminal",
    platform: "copilot-vscode",
    category: "code-action",
    description: "Ask about terminal output, get shell command suggestions, or troubleshoot terminal errors.",
    aliases: [],
    whenToUse: "Use this when you need help with terminal commands, understanding error output, or running shell operations.",
    example: "@terminal how do I find files modified in the last 24 hours?",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_terminal",
    tags: ["participant", "copilot-vscode", "code-action", "terminal", "shell"],
  },
  {
    id: "copilot-vscode-@vscode",
    command: "@vscode",
    platform: "copilot-vscode",
    category: "config",
    description: "Ask about VS Code settings, features, keyboard shortcuts, and extensions.",
    aliases: [],
    whenToUse: "Use this when you need help with VS Code configuration, finding settings, or learning editor features.",
    example: "@vscode how do I enable word wrap?",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_vscode",
    tags: ["participant", "copilot-vscode", "config", "vscode", "editor", "settings"],
  },
  {
    id: "copilot-vscode-@github",
    command: "@github",
    platform: "copilot-vscode",
    category: "integration",
    description: "Search GitHub repositories, issues, pull requests, and use GitHub knowledge to answer questions.",
    aliases: [],
    whenToUse: "Use this when you want to search code on GitHub, look up issues/PRs, or ask questions that benefit from GitHub's code search.",
    example: "@github find examples of MCP server implementations",
    equivalents: [],
    docUrl: "https://code.visualstudio.com/docs/copilot/reference/copilot-vscode-features#_github",
    tags: ["participant", "copilot-vscode", "integration", "github", "search", "issues", "prs"],
  },
];

export const COMMANDS: SlashCommand[] = RAW_COMMANDS.map((command, index) =>
  enrichCommand(command, index)
);
